# Generated by Django 5.1.6 on 2025-02-23 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteItem',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('image', models.UUIDField()),
                ('material', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('NON_RECYCLABLE', 'non_recyclable'), ('RECYCLABLE', 'recyclable'), ('ORGANIC', 'organic')], max_length=255)),
                ('approximate_weight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_waste_items', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_waste_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
