from typing import Protocol

from .entities import WasteItemInfo, Image, WasteItem


class ImageScannerRepository(Protocol):
    def scan(self, image: Image) -> WasteItemInfo: ...

class WasteItemRepository(Protocol):
    def get(self, waste_item_id: str) -> WasteItem: ...
    def save(self, waste_item: WasteItem) -> WasteItem: ...
    def delete(self, waste_item_id: str) -> None: ...
    def list(self) -> list[WasteItem]: ...

class ImageRepository(Protocol):
    def save(self, image: Image) -> str: ...
    def delete(self, image_id: str) -> None: ...
    def get(self, image_id: str) -> str: ...