from typing import Protocol
from uuid import UUID

from .entities import WasteItemInfo, Image, WasteItem
from ..application.dto import StatsWasteItem


class ImageScannerRepository(Protocol):
    def scan(self, image: Image) -> WasteItemInfo: ...

class WasteItemRepository(Protocol):
    def get(self, waste_item_id: str) -> WasteItem: ...
    def create(self, waste_item: WasteItem) -> WasteItem: ...
    def delete(self, waste_item_id: str) -> None: ...
    def list(self) -> list[WasteItem]: ...
    def get_material_count(self, material_waste: str) -> StatsWasteItem: ...
class ImageRepository(Protocol):
    def save(self, image: Image) -> UUID: ...
    def delete(self, image_id: UUID) -> None: ...
    def get(self, image_id: UUID) -> str: ...