from typing import Protocol
from uuid import UUID

from .dtos import UserSignupDto
from .entities import User

class UserRepository(Protocol):
    def create(self, user_dto: UserSignupDto) -> User | None: ...
    def get(self, user_id: UUID) -> User | None: ...
    def list(self) -> list[User]: ...
    def delete(self, user_id: UUID) -> None: ...
    def update(self, user: User) -> User: ...
    def get_by_email(self, email: str) -> User | None: ...
    def get_by_id(self, user_id: UUID) -> User | None: ...