from typing import Protocol
from uuid import UUID

from .entities import User

class UserRepository(Protocol):
    def create(self, user: User) -> User: ...
    def get(self, user_id: UUID) -> User: ...
    def list(self) -> list[User]: ...
    def delete(self, user_id: UUID) -> None: ...
    def update(self, user: User) -> User: ...